### ISSUE TITLE
<updown.fields.RatingManager object at 0x033883F0>

### ISSUE THREAD

**Issue by Huriddin** [weluse/django-updown#14]
Hi, I have a problem intalling the module, I got this error on my template: 
see the title for the error message.

I integrated the module in template as: {{ article.rating }}

and here is my models : 
from django.db import models
from updown.fields import RatingField

class Article(models.Model):
    rating = RatingField(can_change_vote=True)

How can I fix this ? (python 2.7.9)

**Comment by Huriddin** [comment]
also what how can I post to "<object_id>/vote/1" and "<object_id>/vote/-1"  ?

**Comment by dbanck** [comment]
Hi!

`article.rating` is an instance of [`updown.fields.RatingManager`](https://github.com/weluse/django-updown/blob/master/updown/fields.py#L44).
What rating do you want to display? You can show the likes via `{{ article.rating.likes }}` and the dislikes via `{{ article.rating.dislikes }}`.

Have a look at the readme for submitting ratings. There is an example for a video model

**Comment by Huriddin** [comment]
<form action="article/article/rate/(1|-1)">
<form method="post" action="article/{{article.id}}/rate/1" >
{% csrf_token %}
<input type="button" value="Up">
</form>

<form method="post" action="article/{{article.id}}/rate/-1" >
{% csrf_token %}
<input type="button" value="Down">
</form>

<p>Like : {{ article.rating.likes }} // Dislike : {{ article.rating.dislikes }}</p>
</form>

Thanks for your reply but I can't make this work, what is wrong with my template code ?

**Comment by dbanck** [comment]
Do you get any errors?

**Comment by Huriddin** [comment]
no, it just doesn't work when I click submit

**Comment by dbanck** [comment]
Why do you change your comments after I replied? :confused: 

Did you define a Route? It's just a simple GET-Request. You don't need an extra from. A simple ajax request should do it.

**Comment by Huriddin** [comment]
Sorry, I just want to make it clear :/ I have a screenshot of my codes I'll send you
![updown_bak](https://cloud.githubusercontent.com/assets/7415299/6488278/b64b7382-c296-11e4-966a-8f9d2b33829c.jpg)

**Comment by Huriddin** [comment]
No I don't have ajax

**Comment by Huriddin** [comment]
oh wait wrong picutre I'll change it

**Comment by dbanck** [comment]
An input element with `type="button"` won't submit a form. You could use `<input type="submit">`.

**Comment by Huriddin** [comment]
Thanks, I changed that, when I click the page is not found

**Comment by dbanck** [comment]
Did you try calling the url manually? Like `http://your-app/article/1/rate/1` ?
Did you add the required things to your `urls.py`?

**Comment by Huriddin** [comment]
even manually page is not found I can't send you a picture of my views and my url if you want

**Comment by dbanck** [comment]
So did you add this to your `urls.py`?

```
from updown.views import AddRatingFromModel

urlpatterns = patterns("",
    url(r"^(?P<object_id>\d+)/rate/(?P<score>[\d\-]+)$", AddRatingFromModel(), {
        'app_label': 'article',
        'model': 'Article',
        'field_name': 'rating',
    }, name="article_rating"),
)
```

**Comment by Huriddin** [comment]
yes

**Comment by dbanck** [comment]
You've added the rating route to your top-level (`/`), which results in the following url structure: `http://your-app/1/rate/1`.
Better add it to `article.urls`, so you get: `http://your-app/article/1/rate/1`

**Comment by Huriddin** [comment]
yes, I also tried it like this but it still doesn't work :/

**Comment by Huriddin** [comment]
NameError at /article/1/rate/1

name 'AddRatingFromModel' is not defined

**Comment by Huriddin** [comment]
Oh it's okay

**Comment by dbanck** [comment]
Great!

**Comment by Huriddin** [comment]
there is a new problem

**Comment by Huriddin** [comment]
oh you closed it :'(

**Comment by dbanck** [comment]
What new problem?

**Comment by Huriddin** [comment]
Forbidden (403)

CSRF verification failed. Request aborted.

**Comment by dbanck** [comment]
Don't do a POST-Request. Use `<form method="get">`

**Comment by Huriddin** [comment]
Thank you very much it works corretly now ! I really like you sir.

**Comment by dbanck** [comment]
You're welcome (:
