### ISSUE TITLE
Display in template

### ISSUE THREAD

**Issue by alzearafat** [weluse/django-updown#18]
Hi,

How I can display vote (up & down) count on template?

Thank you :)
Regards

**Comment by dbanck** [comment]
Hi!

Inside your template `rating` is an instance of [`updown.fields.RatingManager`](https://github.com/weluse/django-updown/blob/master/updown/fields.py#L44).
You can show the likes via `{{ rating.likes }}` and the dislikes via `{{ rating.dislikes }}`.
