### ISSUE TITLE
Change IPAddressField to GenericIPAddressField for Django==1.9.4

### ISSUE THREAD

**Issue by agusmakmun** [weluse/django-updown#20]
In released 1.0.0 as in changelog says _* Django 1.8 & Django 1.9 are now supported_. But we found the error message when migrate/makemigrations to change `IPAddressField` to `GenericIPAddressField`.

```python
SystemCheckError: System check identified some issues:

ERRORS:
updown.Vote.ip_address: (fields.E900) IPAddressField has been removed except for support in historical migrations.
	HINT: Use GenericIPAddressField instead
```

* and now we work with this, change `updown/models.py`

```python
class Vote(models.Model):
    content_type = models.ForeignKey(ContentType, related_name="updown_votes")
    object_id = models.PositiveIntegerField()
    ...
    ip_address = models.GenericIPAddressField()
```

**Comment by dbanck** [comment]
Good catch! Would you mind creating a PR for this?

Maybe I should write some tests for the models, too.

**Comment by dbanck** [comment]
Thanks for the pull request. I've published a new release to PyPI.

**Comment by agusmakmun** [comment]
U're welcome sir.. :+1:
