### ISSUE TITLE
Template thumbs up and down

### ISSUE THREAD

**Issue by ckgathi** [weluse/django-updown#22]
How do i show the rating on the template?

**Comment by DanielMSchmidt** [comment]
Hi,

Could #18 be an answer to your question?

Have a nice day!

**Comment by heeryung** [comment]
Hi, I have just followed #18 but it didn't work out. Could you help me? I cannot see the ratings on my template. Should I do something in my view file?

This is my urls.py: 
`urlpatterns = [
    url(r'^feedback/display/$', views.feedback_display, name='feedback_display'),
    url(r"^(?P<object_id>\d+)/rate/(?P<score>[\d\-]+)$", AddRatingFromModel(), {'app_label': 'polls', 'model': 'ThumbsUp', 'field_name': 'rating',}, name="response_rating"),
    ]`

This is my template (html):

`{% extends 'polls/base.html' %}
{% block content %}
    <div class="col-lg-6">
        <p> {{ contents_2 }}</p>
        <p> {{ rating.likes }} {{ rating.dislikes }}</p>
    </div>

{% endblock %}`
