### ISSUE TITLE
Migration missing

### ISSUE THREAD

**Issue by baster33** [weluse/django-updown#23]
After making change from this issue: https://github.com/weluse/django-updown/issues/20 there was no migration added for field change, neither was initial fixed to point GenericIPAddress.

**Comment by dbanck** [comment]
Oh, yes. You're right, I guess we missed updating the migration.

Would you mind changing the initial migration to `GenericIPAddressField` and sending a pull request?

**Comment by baster33** [comment]
No problem. I even tried it now, but i don't have access.

**Comment by dbanck** [comment]
Sorry, you don't have access to what?

**Comment by baster33** [comment]
I did `git push origin migration-update` to make new remote branch for pull request and i get
`remote: Permission to weluse/django-updown.git denied to baster33`
Maybe I miss something (it is my first time trying to make pull request to public project repository)

**Comment by dbanck** [comment]
Oh, I see. You can't push on this repository directly. You need to make a fork (copy) of it, make the change there and then submit a pull request.

You can find more and detailed information here: https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by baster33** [comment]
Thank You for instruction. Pull request submitted.

**Comment by dbanck** [comment]
Thanks, I've merged your PR and published a new version! :)
