### ISSUE TITLE
Does this suppport django 1.10?

### ISSUE THREAD

**Issue by nidshar** [weluse/django-updown#25]

**Comment by dbanck** [comment]
Yes and I've added testing for Django 1.10 in ea1f388

**Comment by nidshar** [comment]
I am getting 'Integer out of range'
when i am calling the rating url, what can be the issue?
I am using python 2.7 and django 1.10

**Comment by dbanck** [comment]
Can you provide more information, please? Like a full stack trace and a snippet of your code.
