### ISSUE TITLE
How to check if user has already voted?

### ISSUE THREAD

**Issue by rohitnaidu19** [weluse/django-updown#27]
I dont want user to vote multiple times. How can I check if user has already voted?

**Comment by dbanck** [comment]
We have a builtin check if an user has voted and don't allow voting multiple times. You can even specify if an user is allowed to change its vote.

You can see how this works [here](https://github.com/weluse/django-updown/blob/master/updown/views.py#L38) and [here](https://github.com/weluse/django-updown/blob/master/tests/test_model.py#L44)

I hope this will help :)

**Comment by rohitnaidu19** [comment]
Hey, Thanks a Lot!! :-)
