### ISSUE TITLE
Ratings doesn't show on the template file.

### ISSUE THREAD

**Issue by heeryung** [weluse/django-updown#28]
Hi, I have just followed steps in #18 but it didn't work out. Could you help me? I cannot see the ratings on my template. Should I do something in my view file?

This is my urls.py: 
```
urlpatterns = [
    url(r'^feedback/display/$', views.feedback_display, name='feedback_display'),
    url(r"^(?P<object_id>\d+)/rate/(?P<score>[\d\-]+)$", AddRatingFromModel(), {'app_label': 'polls', 'model': 'ThumbsUp', 'field_name': 'rating',}, name="response_rating"),
    ]
```

This is my template (html):
```
{% extends 'polls/base.html' %}
{% block content %}
    <div class="col-lg-6">
        <p> {{ contents_2 }}</p>
        <p> {{ rating.likes }} {{ rating.dislikes }}</p>
    </div>

{% endblock %}
```

**Comment by dbanck** [comment]
Hi, I need you to provide a little more context.

* Which view is rendering the template? 
* Where do you assign `contents_2` and `rating`?
