### ISSUE TITLE
Bug: MultipleObjectsReturned 

### ISSUE THREAD

**Issue by BouchaaraAdil** [weluse/django-updown#31]
![screen shot 2018-04-09 at 09 47 18](https://user-images.githubusercontent.com/13408745/38488381-3229d582-3bdb-11e8-8fda-eb58c3c3b4f6.png)

**Comment by dbanck** [comment]
Hi!

Do you have more information about this? Did you enter some votes manually into the database?

`django-updown` checks if a vote exists before entering it (https://github.com/weluse/django-updown/blob/master/updown/fields.py#L114), so there shouldn't be any duplicates.

**Comment by BouchaaraAdil** [comment]
Hey @dbanck i'm getting the error above on https://github.com/weluse/django-updown/blob/master/updown/fields.py#L70 line 
maybe someone from the team has added votes manually.

**Comment by BouchaaraAdil** [comment]
@dbanck Thanks Dude i appreciate your help
